# Generated by Django 5.0.6 on 2025-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
